spring.application.name=lichess-backend

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:lichess_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

logging.level.com.autotests.lichessbackend.controller=TRACE
logging.level.com.autotests.lichessbackend.service=DEBUG
logging.level.com.autotests.lichessbackend.exception=ERROR
logging.level.com.autotests.lichessbackend.aspect=TRACE
logging.file.name=logs/lichess-backend.log